### ISSUE TITLE
Remove hardcoded `maxvotes` variable

### ISSUE THREAD

**Issue by DenisCarriere** [eosdac/eosdac-client-legacy#11]
`maxvotes` should be added to a root config or pulled directly on-chain from the `daccustodian::config` table.

https://github.com/eosdac/memberclient/blob/master/src/pages/vote-custodians.vue#L185

![image](https://user-images.githubusercontent.com/550895/54456893-52889680-4736-11e9-9fe7-903d00be62c3.png)

**Comment by piecesnbits** [comment]
added from the contracts config table
