### ISSUE TITLE
Proposals voted on not using the member client stuck in open status

### ISSUE THREAD

**Issue by educatedwarrior** [eosdac/eosdac-client-legacy#110]
In Krown DAC we have some proposals that were voted on using bloks.io and the status didn't update correctly in the client.  Is there a script we can run move these proposals to the correct status?

**Comment by piecesnbits** [comment]
you can manually call the "approvede" (or other) action from the dacmsig contract for each msig you interacted with outside the memberclient.
![image](https://user-images.githubusercontent.com/44613132/66485172-a1b66000-eaa8-11e9-9011-500705d773fc.png)

**Comment by educatedwarrior** [comment]
Looks like someone went into the member client and manually resolved the issue.   @lukestokes , was that you?

**Comment by lukestokes** [comment]
> Looks like someone went into the member client and manually resolved the issue. @lukestokes , was that you?

Nope. Hopefully all is resolved now.

**Comment by michaeljyeates** [comment]
We cannot go in and manually change things, chances are the proposal expired.
