### ISSUE TITLE
Received approvals error

### ISSUE THREAD

**Issue by codecarl84** [eosdac/eosdac-client-legacy#111]
Hello,
The client is not updating  received approvals when proposals are voted on.  We checked the logs on our end and recreated the problem.  Any suggestions would be greatly appreciated. 

Error message
assertion failure with message: approval is not on the list of requested approvals

![image](https://user-images.githubusercontent.com/48947375/67037578-64bf1e80-f0e3-11e9-8897-b111906c17b5.png)

**Comment by piecesnbits** [comment]
this is not an issue from the client but a problem with the api stack. I'll tag @michaeljyeates.
