### ISSUE TITLE
Set profile hardcoded to `dacelections`

### ISSUE THREAD

**Issue by DenisCarriere** [eosdac/eosdac-client-legacy#13]
Should be a global config variable to `daccustodian`

https://github.com/eosdac/memberclient/blob/master/src/pages/profile.vue#L255

**Comment by piecesnbits** [comment]
thanks, for noticing but that is already fixed in the dev branch.
https://github.com/eosdac/memberclient/blob/dev/src/pages/profile.vue#L255
