### ISSUE TITLE
`verifyAndGetRequestedPay` should allow value of 0.0 EOS

### ISSUE THREAD

**Issue by DenisCarriere** [eosdac/eosdac-client-legacy#15]
DAC can setup custodians to request a payment of `0.000 EOS`

https://github.com/eosdac/memberclient/blob/master/src/pages/manage-candidateship.vue#L186-L195

Currently the UI throws an error `requested pay out of range` if 0 is used

**Comment by piecesnbits** [comment]
I think our contract doesn't support 0.0000 EOS because the associating transfer will fail. you can not transfer 0. this should be handled on the contract before allowing 0 in the ui.

**Comment by piecesnbits** [comment]
@dallasjohnson

**Comment by DenisCarriere** [comment]
It does work with 0.0 EOS since I'm running it right now and it seems to work

The custodians pay might need to be modified if pay requests are being sent out, but this shouldn't be a UI issue

**Comment by dallasjohnson** [comment]
I have added a check in the `distributepay` function inside the custodian contract to ensure it doesn't try to transfer any funds if the pay amount has a value of 0.
https://github.com/eosdac/daccustodian/blob/043f6ea6a995600b7b66a541ff1c3a060298ebb5/newperiod_components.cpp#L17 for median pay and https://github.com/eosdac/daccustodian/blob/043f6ea6a995600b7b66a541ff1c3a060298ebb5/newperiod_components.cpp#L46 for mean pay. The mean pay is a new direction in how to calculate the pay. I have kept both options in the code to allow flexibility for others (although at this stage it would still require a code change to switch between them). 
So with this check I believe it should be fine but please let me know if you see any issues with this.

**Comment by piecesnbits** [comment]
I changed the check for >= 0.
