### ISSUE TITLE
Jungle bloks.io explorer hard coded

### ISSUE THREAD

**Issue by DenisCarriere** [eosdac/eosdac-client-legacy#17]
https://github.com/eosdac/memberclient/blob/master/src/store/user/actions.js#L183

**Comment by piecesnbits** [comment]
thanks :-) this too is fixed already fixed in the dev branch.

**Comment by DenisCarriere** [comment]
Good to know! 👍 

I should of forked from the `dev` branch, didn't know there was so many fixes

**Comment by piecesnbits** [comment]
yeah the two hardcoded variables were discovered yesterday by @michaeljyeates. better to inspect the dev branch atm we only merged in to master to deploy on our staging server. this version of the memberclient isn't in production yet. so having code in the master branch is a bit misleading. sorry :-)

**Comment by DenisCarriere** [comment]
Once everything is merged to `master`, i'll do another pass at it
