### ISSUE TITLE
Allow `getMemberStatus` to have balance of 0.0 DAC tokens

### ISSUE THREAD

**Issue by DenisCarriere** [eosdac/eosdac-client-legacy#18]
Members who have voted and have 0.0 DAC should be considered as members.

https://github.com/eosdac/memberclient/blob/dev/src/store/user/getters.js#L49-L54

**Comment by piecesnbits** [comment]
at eosdac you're considered to be an active member only if you have a positive eosdac balance. else you're account is in a pending state.

**Comment by DenisCarriere** [comment]
@piecesnbits oh really? Ok well if that's the case, then we can close this issue then 👍

**Comment by piecesnbits** [comment]
![image](https://user-images.githubusercontent.com/44613132/54475904-444e7f00-47f7-11e9-9563-19bf0eaeb258.png)
:-)

**Comment by DenisCarriere** [comment]
There is an edge case for custodians, they could stake the full amount and still have a 0 balance.

But if owning 0.0 DAC tokens makes the user pending, then that's fair
