### ISSUE TITLE
When no new proposals to sign, this page looks odd.

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client-legacy#3]
![image](https://user-images.githubusercontent.com/344748/53843905-5cfaa180-3f7a-11e9-8a25-cd5439afe15b.png)

Maybe add some text to it when things are empty?

**Comment by piecesnbits** [comment]
yeah that's one of the pages that doesn't have code yet... I only made the route with an empty page as preparation...

**Comment by lukestokes** [comment]
Ah, okay. :)
