### ISSUE TITLE
Refresh custodian pay page after claiming pay

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client-legacy#32]
May be related to https://github.com/eosdac/memberclient/issues/26 also.

Might be good to go through the app and figure out which pages change state after a successful scatter transaction completes and then update the page accordingly. I get that some things will not show up yet because of it's not in an irreversible block, but maybe some things are that big of a deal?

**Comment by piecesnbits** [comment]
this is already fixed in dev

**Comment by lukestokes** [comment]
BOOM! You rock. :)
