### ISSUE TITLE
Feature Request: Add the ability to vote for eosdacserver even if not a member

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client-legacy#4]
This may be a bit tricky, but can we add access to the "vote for eosdac" button even if they haven't signed the constitution? We were also thinking it might make sense on the home page of the member client. The idea is we'd just send people to our member client to vote for us instead of sending them to bloks.io like the beta site does now. That way anyone who comes to our website can just click over to the member client and vote for us, even if they don't intend to read the constitution and join the DAC.

Is that doable?

**Comment by piecesnbits** [comment]
yes they need to be logged in though... I didn't do the BP voting stuff yet. so i'll implement the button from the old client.

**Comment by piecesnbits** [comment]
personally I think it's even better to have the vote for eosdacserver on the website instead of in the client. and link the other way around.

**Comment by lukestokes** [comment]
@piecesnbits I thought we agreed to keep the website clear of any chain integration? Now that they are both hosted on the same server and don't have the concerns about wordpress hacks, maybe we should re-evaluate this. What do you think, @michaeljyeates? Should we include eosjs to the static site and add direct voting there instead? Andrew was thinking this was a better approach also but I had thought we agreed to not go that direction to limit the potential attack surface. Maybe it's time to re-evaluate?

**Comment by lukestokes** [comment]
Spoke with @michaeljyeates today and it looks like he's onboard with getting voting going on the main website. Let's move that direction instead.
