### ISSUE TITLE
Install with `npm install` didn't work

### ISSUE THREAD

**Issue by DenisCarriere** [eosdac/eosdac-client-legacy#5]
Very strange, I installed the repo with `npm install`, however it didn't want to build afterwards (`quasar build`)

```
$ node -v
v11.9.0
$ npm -v
6.7.0
```

**Workaround solution**
Install with `yarn` using your `yarn.lock` file it worked.

Strange.. 🤔 This means some dependencies installed with `npm` prevents from building.

Feel free to close this issue, since it might be out of scope of this project.

**Comment by piecesnbits** [comment]
yeah npm is not working very smooth with quasar... it's recommended by quasar to use yarn.
