### ISSUE TITLE
Every time I load the new worker proposal window, the category menu labels gets messed up

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-client-legacy#59]
![image](https://user-images.githubusercontent.com/344748/57879551-c4d72f00-77ea-11e9-8423-b4b48ee89a25.png)

**Comment by lukestokes** [comment]
Shows up here too:
![image](https://user-images.githubusercontent.com/344748/57882478-cf48f700-77f1-11e9-9961-6f7f966d996c.png)

**Comment by piecesnbits** [comment]
should be fixed
