### ISSUE TITLE
Immutable totalsupply value

### ISSUE THREAD

**Issue by tim-yyd** [eosdac/eosdac-client-legacy#76]
calculate VotingProgress value(in display-custodians.vue file),  let totalsupply = 1000000000.0 * 10000; set the Immutable totalsupply value.

**Comment by piecesnbits** [comment]
thanks, that is fix in our dev branch. thank you!
https://github.com/eosdac/eosdac-client/commit/21feca6938582bb6b8fd6fcd96419ad448918926
