### ISSUE TITLE
disable the paying feature at all if requested_pay_max = 0

### ISSUE THREAD

**Issue by str** [eosdac/eosdac-client-legacy#88]
While some DACs decide how much they will be able to pay or if they are going to pay the custodinas at all, they can set the requested_pay_max = 0.  

If that's the case, showing how much to request when suscribing as a custodian could confuse someone.   

Please, if requested_pay_max = 0, hide all payments related stuff.

**Comment by piecesnbits** [comment]
I have hidden the my payments and requested_pay in the UI when requested pay max is 0.
