### ISSUE TITLE
Allow for other types of logo image

### ISSUE THREAD

**Issue by michaeljyeates** [eosdac/eosdac-client-legacy#90]
Currently the member client is hard coded to use svg for the logos, this could be any image type

**Comment by michaeljyeates** [comment]
Think this will probably be solved by #89

**Comment by piecesnbits** [comment]
logos can be loaded via the theme file and can from an other domain. https://github.com/eosdac/eosdac-client-extension/commit/c42e96bae3ec4b20510d8e21f64dd54464135d41
